language: java
node_js:
  - "0.10"

before_script:
  - cd www
  - npm install -g bower
  - npm install
  - bower install -f
  - cd ..

script: gradle build

notifications:
  email:
    recipients:
      - ajay.samgir@krishagni.com
    on_success: always
    on_failure: always


branches:
  only:
    - OS_v20_Travis_Setup
    
before_deploy:
  - export RELEASE_FILE=$(ls build/libs/*.war)
  - echo "Deploying $RELEASE_FILE to GitHub"

deploy:
  provider: releases

  api_key:
    secure: \nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCMbbw9W7EhEpELFFnjVuL1smWi\nYMZI1JBqLNHRtySP4r9MQGKro2NQ51/1fGVsfpJ+mHjf53sH+0ZXQI0ruLpnbydj\n7Do1PEBeifrucQAqRN72ktmZxuFNhxGailJY6zMOL8aIghYDIs0XpLlrAgG2a/Y5\nKtJFVxkB10svS2wG2wIDAQAB\n

  file:
    - "${RELEASE_FILE}"
  
  skip_cleanup: true

  on:
    repo: krishagni/openspecimen
    
